### PR TITLE
Verbose logging only if in debug mode

### LINKED ISSUE #56: Problem with pulseaudio on Docker Container hassio_audio
Any one, any idea to my following problem?

My Setup:
Raspberri Pi 4 4GB
VERSION="10 (buster)"
Docker 20.10.5

HomeAssistant (Docker based install via IOTstack):
core-2021.3.3
supervisor-2021.03.4

I found in /var/log/user.log and the log of the docker container hassio_audio this dialog, repeatly each second:

Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] core-util.c: setpriority() worked.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] core-util.c: Successfully gained nice level -11.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Found user 'root' (UID 0) and group 'root' (GID 0).
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] main.c: Home directory of user 'root' is not '/var/run/pulse', ignoring.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Successfully changed user to "root".
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: This is PulseAudio 14.2
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Compilation CFLAGS: Not yet supported on meson
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Running on host: Linux armv7l 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Found 4 CPUs.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Page size is 4096 bytes
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Compiled with Valgrind support: no
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Running in valgrind mode: no
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Running in VM: no
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Running from build tree: no
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Optimized build: yes
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: All asserts enabled.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Machine ID is d523c2695600425ea81b9a041c6f37f6.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Using runtime directory /var/run/pulse.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Using state directory /data/states.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-14.2/modules.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Running in system mode: yes
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] pid.c: Stale PID file, overwriting.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: System supports high resolution timers
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] memblock.c: Using private memory pool with 1024 slots of size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is 65496
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] cpu-arm.c: CPU flags: V6 V7 VFP EDSP NEON VFPV3
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] svolume_arm.c: Initialising ARM optimized volume functions.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] sconv_neon.c: Initialising ARM NEON optimized conversions.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] mix_neon.c: Initialising ARM NEON optimized mixing functions.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] remap_neon.c: Initialising ARM NEON optimized remappers.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/d523c2695600425ea81b9a041c6f37f6-device-volumes.tdb'
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] database.c: Successfully opened 'device-volumes' database file '/data/states/d523c2695600425ea81b9a041c6f37f6-device-volumes.tdb'.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] module.c: Loaded "module-device-restore" (index: #0; argument: "").
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/d523c2695600425ea81b9a041c6f37f6-stream-volumes.tdb'
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] database.c: Successfully opened 'stream-volumes' database file '/data/states/d523c2695600425ea81b9a041c6f37f6-stream-volumes.tdb'.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] protocol-dbus.c: Interface org.PulseAudio.Ext.StreamRestore1 added for object /org/pulseaudio/stream_restore1
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] module.c: Loaded "module-stream-restore" (index: #1; argument: "").
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/d523c2695600425ea81b9a041c6f37f6-card-database.tdb'
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] database.c: Successfully opened 'card-database' database file '/data/states/d523c2695600425ea81b9a041c6f37f6-card-database.tdb'.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] module.c: Loaded "module-card-restore" (index: #2; argument: "").
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] module.c: Loaded "module-switch-on-port-available" (index: #3; argument: "").
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] module.c: Loaded "module-switch-on-connect" (index: #4; argument: "").
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] module-udev-detect.c: /dev/snd/controlC0 is accessible: yes
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] module-udev-detect.c: Failed to open /proc/asound/card0: No such file or directory
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] module-udev-detect.c: /devices/platform/soc/fe00b840.mailbox/bcm2835_audio/sound/card0 is busy: no
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: E: [pulseaudio] core-rtclock.c: Assertion 'clock_gettime(CLOCK_REALTIME, &ts) == 0' failed at ../src/pulsecore/core-rtclock.c:93, function pa_rtclock_get(). Aborting.

### LINKED ISSUE #57: hassio_audio proper log handling, less spamming
## Problem    

The ```hassio_audio``` container continuously outputs info and debug data, that puts unnecessary load on downstream systems and contribute to reducing the lifespan of SD's / SSD's.
It is not possible (to my knowledge) to set the log level for ```hassio_audio```. It does not seem to support the Home Assistant standard that allows the log level to be set in the Logger Integration in ```configuration.yaml```, as explained in the [Logger documentation](https://www.home-assistant.io/integrations/logger).

## Request    

1) Remove the ```-vvv``` PulseAudio run parameter, to make the output less verbose. Or make it configurable.
2) Add a timestamp to the PulseAudio messages ```--log-time[=BOOL]```
3) Set the correct level for stdout / stderr messages raised to journald. Currently ALL ```hassio_audio``` messages are raised as level 3 (i.e. error), whether "D" (debug), "I" (info), or "E" (error).
4) Support the Logger directive to allow the user to set the output log level, e.g. critical / error / info / debug.    
   Maybe this can be achieved using the "--log-level" PulseAudio command parameter? 

#### Home Assistant logger filter setting has no effect on ```hassio_audio```

Current logger settings in ```configuration.yaml```.
```
logger:
  default: critical
  logs:
    homeassistant.core: fatal
```

Even with the log settings above, below are typical "D" (debug) and "I" (info) messages output by ```hassio_audio```, retrieved from the Docker logs for the container. The "critical" default setting has no effect on the filtering of messages from ```hassio_audio```. Or is there an (undocumented) setting that actually works to filter only real error messages?

```
docker logs audio_hassio
...
I: [pulseaudio] client.c: Created 14 "Native client (UNIX socket client)"
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.
D: [pulseaudio] protocol-native.c: Protocol version: remote 34, local 34
D: [pulseaudio] protocol-native.c: SHM possible: no
D: [pulseaudio] protocol-native.c: Negotiated SHM: no
D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support
I: [pulseaudio] client.c: Freed 14 "supervisor"
I: [pulseaudio] protocol-native.c: Connection died.
...

```
#### ```hassio_audio``` raises ALL messages as errors, regardless of their real level.

Below are the same ```hassio_audio``` log records, this time retrieved using journalctl.
NOTE: 
- In the journalctl command below **only errors were retrieved** (parameter ```-p err```).
- The messages returned from journalctl are information ("I") and debug ("D") level messages, but with an error log level.

```
journalctl CONTAINER_NAME=hassio_audio -p err

-- Logs begin at Mon 2021-03-08 22:43:29 CET, end at Sat 2021-03-13 12:44:51 CET. --
...
Mar 10 00:05:12 RPiHome 5941937722e7[584]: I: [pulseaudio] client.c: Created 14 "Native client (UNIX socket client)"
Mar 10 00:05:12 RPiHome 5941937722e7[584]: I: [pulseaudio] protocol-native.c: Client authenticated anonymously.
Mar 10 00:05:12 RPiHome 5941937722e7[584]: D: [pulseaudio] protocol-native.c: Protocol version: remote 34, local 34
Mar 10 00:05:12 RPiHome 5941937722e7[584]: D: [pulseaudio] protocol-native.c: SHM possible: no
Mar 10 00:05:12 RPiHome 5941937722e7[584]: D: [pulseaudio] protocol-native.c: Negotiated SHM: no
Mar 10 00:05:12 RPiHome 5941937722e7[584]: D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support
Mar 10 00:05:12 RPiHome 5941937722e7[584]: I: [pulseaudio] client.c: Freed 14 "supervisor"
Mar 10 00:05:12 RPiHome 5941937722e7[584]: I: [pulseaudio] protocol-native.c: Connection died.
...
```

And the first record from the above output, now shown verbose to confirm ```PRIORITY=3```:

```
journalctl CONTAINER_NAME=hassio_audio --since "2021-03-10 00:05:00" --until "2021-03-10 00:06:00" -o verbose

-- Logs begin at Mon 2021-03-08 22:43:29 CET, end at Sat 2021-03-13 12:44:51 CET. --
Wed 2021-03-10 00:05:12.194229 CET [s=e0ae8b76d4cd495caeca4d33ba3702ea;i=2ba;b=285f795042f04f8588bbdd5ce295afd7;m=15418de86b;t=5bd22952310d4;x=37ce5b2c89d83e4]
    _BOOT_ID=285f795042f04f8588bbdd5ce295afd7
    _MACHINE_ID=be042b18af4b495ca4957bfef9e53bfd
    _HOSTNAME=RPiHome
    _UID=0
    _GID=0
    _SYSTEMD_SLICE=system.slice
    _TRANSPORT=journal
    _CAP_EFFECTIVE=1ffffffffff
    PRIORITY=3
    _PID=584
    _COMM=dockerd
    _EXE=/usr/bin/dockerd
    _CMDLINE=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
    _SYSTEMD_CGROUP=/system.slice/docker.service
    _SYSTEMD_UNIT=docker.service
    _SYSTEMD_INVOCATION_ID=02eb6c5d4ad24576bd16a7252e7c8803
    CONTAINER_NAME=hassio_audio
    CONTAINER_TAG=5941937722e7
    IMAGE_NAME=homeassistant/armv7-hassio-audio:2021.02.1
    SYSLOG_IDENTIFIER=5941937722e7
    CONTAINER_ID=5941937722e7
    CONTAINER_ID_FULL=5941937722e730a3f0045de4a539addcca6209c9ef10d227499d2d843bebe0e0
    MESSAGE=I: [pulseaudio] client.c: Created 14 "Native client (UNIX socket client)"
    _SOURCE_REALTIME_TIMESTAMP=1615331112194229
...
```

### PR DESCRIPTION
**Pull request by mdegat01**
Only do verbose logging if supervisor is in debug mode, otherwise drop `-vvv` from command.

Parent PR: https://github.com/home-assistant/supervisor/pull/3752

Supercedes #85 

Fixes #57
Fixes #56

### CODE REVIEW

File: rootfs/etc/services.d/pulseaudio/run [hunk 1]
```diff
@@ -5,4 +5,11 @@
 export PULSE_STATE_PATH="/data/states"
 export LD_PRELOAD="/usr/local/lib/libjemalloc.so.2"
 
-exec pulseaudio --system -vvv --disallow-exit --exit-idle-time=-1 --disable-shm
+debug="$(jq '.debug' /config/plugin_audio.json)"
+log_level=""
+
+if [ "$debug" == 'true']; then
```
Comment (agners) [inline rootfs/etc/services.d/pulseaudio/run:11]:
```suggestion
if [ "$debug" = "true" ]; then
```

Space before `]` seems to be required. Single `=` is more POSIX. Quotes probably doesn't matter, but is nicer IMHO.

**Review by agners — CHANGES_REQUESTED** [review]

**Review by agners — APPROVED** [review]

File: rootfs/etc/services.d/pulseaudio/run [hunk 2]
```diff
@@ -5,4 +5,11 @@
 export PULSE_STATE_PATH="/data/states"
 export LD_PRELOAD="/usr/local/lib/libjemalloc.so.2"
 
-exec pulseaudio --system -vvv --disallow-exit --exit-idle-time=-1 --disable-shm
+debug="$(jq '.debug' /config/plugin_audio.json)"
```
Comment (pvizeli) [inline rootfs/etc/services.d/pulseaudio/run:8]: Let's use bashio

File: rootfs/etc/services.d/pulseaudio/run [hunk 3]
```diff
@@ -5,4 +5,11 @@
...
+log_level=""
+
+if [ "$debug" = "true" ]; then
```
Comment (pvizeli) [inline rootfs/etc/services.d/pulseaudio/run:11]: for this too
